"use strict";
/**
 * Accomodae API
 * RESTful API for Accomodae service
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.UsersIdListingsPostRequest = void 0;
class UsersIdListingsPostRequest {
    static getAttributeTypeMap() {
        return UsersIdListingsPostRequest.attributeTypeMap;
    }
}
exports.UsersIdListingsPostRequest = UsersIdListingsPostRequest;
UsersIdListingsPostRequest.discriminator = undefined;
UsersIdListingsPostRequest.attributeTypeMap = [
    {
        "name": "title",
        "baseName": "title",
        "type": "string"
    },
    {
        "name": "description",
        "baseName": "description",
        "type": "string"
    },
    {
        "name": "price",
        "baseName": "price",
        "type": "number"
    }
];
