/**
 * Accomodae API
 * RESTful API for Accomodae service
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class UsersPostRequest {
    'username'?: string;
    'password'?: string;
    'role'?: UsersPostRequest.RoleEnum;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "username",
            "baseName": "username",
            "type": "string"
        },
        {
            "name": "password",
            "baseName": "password",
            "type": "string"
        },
        {
            "name": "role",
            "baseName": "role",
            "type": "UsersPostRequest.RoleEnum"
        }    ];

    static getAttributeTypeMap() {
        return UsersPostRequest.attributeTypeMap;
    }
}

export namespace UsersPostRequest {
    export enum RoleEnum {
        Student = <any> 'student',
        PropertyOwner = <any> 'property_owner',
        WebsiteAdmin = <any> 'website_admin'
    }
}
