"use strict";
/**
 * Accomodae API
 * RESTful API for Accomodae service
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.UsersPostRequest = void 0;
class UsersPostRequest {
    static getAttributeTypeMap() {
        return UsersPostRequest.attributeTypeMap;
    }
}
exports.UsersPostRequest = UsersPostRequest;
UsersPostRequest.discriminator = undefined;
UsersPostRequest.attributeTypeMap = [
    {
        "name": "username",
        "baseName": "username",
        "type": "string"
    },
    {
        "name": "password",
        "baseName": "password",
        "type": "string"
    },
    {
        "name": "role",
        "baseName": "role",
        "type": "UsersPostRequest.RoleEnum"
    }
];
(function (UsersPostRequest) {
    let RoleEnum;
    (function (RoleEnum) {
        RoleEnum[RoleEnum["Student"] = 'student'] = "Student";
        RoleEnum[RoleEnum["PropertyOwner"] = 'property_owner'] = "PropertyOwner";
        RoleEnum[RoleEnum["WebsiteAdmin"] = 'website_admin'] = "WebsiteAdmin";
    })(RoleEnum = UsersPostRequest.RoleEnum || (UsersPostRequest.RoleEnum = {}));
})(UsersPostRequest || (exports.UsersPostRequest = UsersPostRequest = {}));
