"use strict";
/**
 * Accomodae API
 * RESTful API for Accomodae service
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.UsersAuthenticatePostRequest = void 0;
class UsersAuthenticatePostRequest {
    static getAttributeTypeMap() {
        return UsersAuthenticatePostRequest.attributeTypeMap;
    }
}
exports.UsersAuthenticatePostRequest = UsersAuthenticatePostRequest;
UsersAuthenticatePostRequest.discriminator = undefined;
UsersAuthenticatePostRequest.attributeTypeMap = [
    {
        "name": "username",
        "baseName": "username",
        "type": "string"
    },
    {
        "name": "password",
        "baseName": "password",
        "type": "string"
    }
];
